/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3Dmodels/front.glb -o src/components/FrontT.jsx -r public 
*/
import { Center, Decal, useGLTF, useTexture } from "@react-three/drei";
import { useEffect, useRef } from "react";

export function FrontT({ tshirtColor, designTexture, onViewChange }) {
  const texture = useTexture(designTexture || "/2.webp");
  const { nodes, materials } = useGLTF("/3Dmodels/front.glb");
  const meshRef = useRef();

  useEffect(() => {
    if (meshRef.current) {
      meshRef.current.material.color.set(tshirtColor); // ✅ Dynamically update color
    }
  }, [tshirtColor]);

  const handleClick = () => {
    onViewChange("front");
  };

  return (
    <Center>
      <group dispose={null}>
        <group scale={0.09} position={[0, -1, 5]}>
          <mesh
            geometry={nodes.Object_0.geometry}
            material={materials.material}
            ref={meshRef}
          />
          <mesh geometry={nodes.Object_0_1.geometry}>
            <meshBasicMaterial />
            {/* Adjusted to non-transparent */}
            <Decal
              // debug // Makes "bounding box" of the decal visible
              position={[0, 30, 15]} //{pos} // Position of the decal
              rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
              scale={[65, 65, 35]} //{scale} // Scale of the decal
              onClick={handleClick}
            >
              <meshStandardMaterial
                map={texture}
                toneMapped={false}
                transparent
                polygonOffset
                polygonOffsetFactor={-1} // The mesh should take precedence over the original
                // side={2} // DoubleSide
                // alphaTest={0.1}
                // depthTest={true} // Ensure depth testing is enabled
              />
            </Decal>
          </mesh>
        </group>
        {/* <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.material_1}
        scale={0.011}
      /> */}
      </group>
    </Center>
  );
}

useGLTF.preload("/3Dmodels/front.glb");
