/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3Dmodels/front.glb -o src/components/FrontT.jsx -r public 
*/
import { Center, Decal, useGLTF, useTexture } from "@react-three/drei";

export function FrontT(props) {
  const texture = useTexture("/2.webp");
  const { nodes, materials } = useGLTF("/3Dmodels/front.glb");

  return (
    <Center>
      <group {...props} dispose={null}>
        <group scale={0.09} position={[0, -1, 5]}>
          <mesh
            geometry={nodes.Object_0.geometry}
            material={materials.material}
          />
          <mesh geometry={nodes.Object_0_1.geometry}>
            <meshBasicMaterial transparent opacity={0} />
            <Decal
              // debug // Makes "bounding box" of the decal visible
              position={[0, 30, 15]} //{pos} // Position of the decal
              rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
              scale={[65, 65, 35]} //{scale} // Scale of the decal
            >
              <meshStandardMaterial
                map={texture}
                toneMapped={false}
                transparent
                polygonOffset
                polygonOffsetFactor={-1} // The mesh should take precedence over the original
              />
            </Decal>
          </mesh>
        </group>
        {/* <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.material_1}
        scale={0.011}
      /> */}
      </group>
    </Center>
  );
}

useGLTF.preload("/models/front.glb");
